blogapp/urls.py
from django.urls import path
from .views import post_delete, post_detail, post_list, post_create, post_update, like
app_name = "blogapp"
urlpatterns = [
    path("", post_list, name="list" ),
    path("create", post_create, name="create" ),
    path("<str:slug>/", post_detail, name="detail" ),
    path("<str:slug>/update", post_update, name="update" ),
    path("<str:slug>/delete", post_delete, name="delete" ),
    path("<str:slug>/like/",like, name="like"),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blogapp.urls")),
    path("users/", include("users.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>

{% load static  %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blogapp/css/style.css' %}"/>
    <title>Blog App</title>
</head>
<body>
    
    {% include "navbar.html" %}
    <div>
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == "error" %}
        <div class="alert alert-danger">{{ message }}</div>
        {% else %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endif %}
        {% endfor %}
        {% endif %}
        
        {% block content %}
        
        {% endblock content %}

    
    <!-- JAVASCRIPT / BOOTSTRAP -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<script src="{% static 'blogapp/static/myapp/js/timeout.js' %}"></script>
<script src="https://kit.fontawesome.com/74c8282b8a.js" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
{% load static %}


{% block content %}
<nav class="mb-5 px-4  navbar navbar-expand-md navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blogapp:list'  %}"">
          <h3>BLOG APP</h3>
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">            
             {% if not request.user.is_authenticated %} 
            <li class="nav-item">
              <a class="nav-link"  href="{% url 'login' %}">Login</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link " href="{% url 'blogapp:list'  %}">Home</a>
            </li>            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogapp:create' %}">New Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    
{% endblock content %}
    