blogapp/urls.py
from django.urls import path
from .views import post_delete, post_detail, post_list, post_create, post_update, like
app_name = "blogapp"
urlpatterns = [
    path("", post_list, name="list" ),
    path("create", post_create, name="create" ),
    path("<str:slug>/", post_detail, name="detail" ),
    path("<str:slug>/update", post_update, name="update" ),
    path("<str:slug>/delete", post_delete, name="delete" ),
    path("<str:slug>/like/",like, name="like"),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blogapp.urls")),
    path("users/", include("users.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/models.py
from email.policy import default
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
def user_directory_path(instance, filename):
    return "blog/{0}/{1}".format(instance.author.id, filename)

class Category(models.Model):
    name = models.CharField(max_length=30)

    class Meta():
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Post(models.Model):
    OPTIONS = (
        ("dr", "Draft"),
        ("pb", "Puplished")
    )
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to=user_directory_path, default="django.jpg")
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    puplish_date = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=OPTIONS, default="dr") 
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title

    def comment_count(self):
        return self.comment_set.all().count()
    
    def view_count(self):
        return self.postview_set.all().count()
    
    def like_count(self):
        return self.like_set.all().count()

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return self.user.username
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

blogapp/forms.py
from random import choices
from django import forms
from.models import Category, Post, Comment

class PostForm(forms.ModelForm):
    status = forms.ChoiceField(choices = Post.OPTIONS)
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(), empty_label="Select")
    class Meta:
        model = Post
        fields = (
            "title",
            "content",
            "image",
            "category",
            "status",
        )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

blogapp/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Post, Like, PostView
from .forms import CommentForm, PostForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.
def post_list(request):
    posts = Post.objects.filter(status="pb")
    context =  {
        "posts" : posts
    }
    return render(request, "blogapp/post_list.html", context)
    
@login_required
def post_create(request):
    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)    
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request,"Post created successfully!" )
            return redirect("blogapp:list")

    context = {
        "form": form
    }
    return render(request, "blogapp/post_create.html", context )


def post_detail(request, slug):
    post =get_object_or_404(Post, slug = slug)
    form = CommentForm()
    if request.user.is_authenticated:
        PostView.objects.get_or_create(user=request.user, post = post)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post =  post
            comment.save()
            return redirect("blogapp:detail", slug=slug)
            #return redirect(request.path)       
    context = {
        "post": post,
        "form":form
         }
    return render(request, "blogapp/post_detail.html", context)

@login_required   
def post_update(request, slug):
    post = Post.objects.get(slug = slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if request.user != post.author:
        messages.warning(request,"You are not a writer of this post!" )
        return redirect("blogapp:list")
    if form.is_valid():
        form.save()
        messages.success(request,"Post updated successfully!" )
        return redirect("blogapp:list")

    context = {
        "post" : post,
        "form": form

    }
    return render(request, "blogapp/post_update.html", context)

@login_required   
def post_delete(request, slug):
    post = Post.objects.get(slug = slug)
    if request.user != post.author:
        messages.warning(request,"You are not a writer of this post!" )
        return redirect("blogapp:list")
    if request.method == "POST":
        post.delete()
        messages.success(request,"Post deleted successfully!" )
        return redirect("blogapp:list")
    return render(request, "blogapp/post_delete.html", {"post" : post})

@login_required()
def like(request, slug):
    if request.method == "POST":
        obj = get_object_or_404(Post, slug=slug)
        like_qs = Like.objects.filter(user=request.user, post=obj)
        if like_qs.exists():
            like_qs[0].delete()
        else:
            Like.objects.create(user=request.user, post=obj)
        return redirect("blogapp:detail", slug=slug)
    return redirect("blogapp:detail", slug=slug)

blogapp/templates/blogapp/post_create.html
{% extends 'base.html' %} {% block content %}
<div class="container d-flex justify-content-center mt-5">
  <div class="newblog-container">
    <div>
      <h2 class="mb-3 text-center">Blog Post</h2>
    </div>
    <div>
      {% load crispy_forms_tags %}
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ form | crispy }}
        <div class="text-center mt-3">
          <input type="submit" value="Post" class="mt-2 btn btn-info w-25" />
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

blogapp/templates/blogapp/post_delete.html
{% extends 'base.html' %} {% block content %}
<div class="newblog-container w-50 text-center">
  <form action="" method="POST" class="m-2">
    <h5>Are You Sure delete {{ post.title }}!</h5>
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-success" />
  </form>

  <a href="{% url 'blogapp:list' %}">
    <button class="btn btn-warning m-1">No</button>
  </a>
</div>

{% endblock content %}

blogapp/templates/blogapp/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="container d-flex justify-content-center mt-5">
  <div class="container detail-container p-4">
    <div>
      <h2 class="mb-3 text-center">Post Detail</h2>
      <br>
    </div>
          {% if post.image %}
          <img src="{{ post.image.url }}" class="card-img-top w-100" alt="image">

          {% else %}
          
          <img src="media/django.png" class="card-img-top w-100  " alt="image">
        {% endif %}


    <div class="card-body">
      <h5 class="card-title">{{post.title}}</h5>
      <p class="card-text" >{{post.content | truncatechars:20}}</p>
      <div>
          <span><i class="far fa-comment-alt mx-1"></i></i> {{ post.comment_count }}</span>
                <span><i class="fas fa-eye mx-1"></i> {{ post.view_count }}</span>
                <span><i class="far fa-heart mx-1"></i> {{ post.like_count }}</span>
                <span class="float-right mx-2"> <small>Posted {{ post.publish_date | timesince }} ago.</small> </span>
      </div>
      <hr>
      <div>
            <h4>Enjoy this post? Give it a LIKE!!</h4>
      </div>
      <div>
          <form action="{% url 'blogapp:like' post.slug %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="post">
                <input type="hidden" name="user">
                
                <button class="btn btn-outline-danger" type="submit">Like it!</button>               
          </form>
          <hr>
          <h4>Leave a comment below</h4>
          <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-info btn-sm mt-2">SEND</button>
            </form>
            <hr>
            <h4>Comments</h4>
            {% for comment in post.comments %}
            <div>
                <p>
                    <small><b>Comment by {{comment.user}}</b></small> - <small>{{ comment.time_stamp|timesince }} ago.
                    </small>
                </p>
                <p>
                    {{ comment.content }}
                </p>
            </div>
            <hr>
            {% endfor %}


      </div>
            
      <div class="text-center">
      {% if user.id == post.author.id %}
        <a href="{% url 'blogapp:update' post.slug %}" class="btn btn-info m-2 w-25">Edit</a>
        <a href="{% url 'blogapp:delete' post.slug %}" class="btn btn-danger m-2 w-25">Delete</a>
      {% else %}      
        <a href="{% url 'blogapp:list' %}" class="btn w-50 btn-danger m-2">Back</a>
      </div>
      
      {% endif %}
        
      
    </div>
  </div>
</div>

    
{% endblock content %}

blogapp/templates/blogapp/post_list.html
{%extends 'base.html' %} {% load static %} {% block content %}
<div class="mt-5 mb-3">
  <div>
    <h1 class="text-center pt-4">Blog App</h1>
  </div>
  <br />
  <div class="card-container">
    <div
      class="row row-cols-1 row-cols-md-3 row-cols-lg-4 g-4 justify-content-center"
    >
      {% for post in posts %}
      <div class="col d-flex justify-content-center">
        <div class="card p-2">
          {% if post.image %}
          <img
            src="{{ post.image.url }}"
            class="card-img-top w-100"
            style="height: 9rem"
            alt="image"
          />
          {% else %}
          <img
            src="media/django.png"
            class="card-img-top w-100"
            style="height: 9rem"
            alt="image"
          />
          {% endif %}

          <div class="card-body">
            <h5 class="card-title">{{post.title}}</h5>
            <p class="card-text">{{post.content | truncatechars:20}}</p>
            <p>
              <span>
                <i class="far fa-comment-alt mx-1"></i>
                {{post.comment_count}}
              </span>
              <span><i class="fas fa-eye mx-1"></i>{{ post.view_count }}</span>
              <span
                ><i class="far fa-heart mx-1"></i>{{ post.like_count }}</span
              >
            </p>
          </div>
          <div class="card-footer">
            <small class="text-muted"
              >Posted {{ post.puplish_date | timesince }} ago.
            </small>
          </div>
          <div class="text-center p-2">
            <a href="{% url 'blogapp:detail' post.slug %}">
              <button type="button" class="btn btn-info w-50">Details</button>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}

blogapp/templates/blogapp/post_update.html
{% extends 'base.html' %} {% block content %}

<div class="container d-flex justify-content-center mt-5">
  <div class="newblog-container">
    <div>
      <h4 class="mb-3 text-center">Update Post</h4>
    </div>
    <div>
      {% load crispy_forms_tags %}
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ form | crispy }}
        <div class="text-center mt-3">
          <input type="submit" value="Post" class="mt-2 btn btn-info w-25" />
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock content %}